import { ShaderData } from "@/types/shader";
import fullscreenVert from "@/shaders/fullscreen.vert.glsl";
import default2dFrag from "@/shaders/default2d.frag.glsl";
import default3dVert from "@/shaders/default3d.vert.glsl";
import default3dFrag from "@/shaders/default3d.frag.glsl";
import blueGlitchFrag from "@/shaders/blue-glitch.frag.glsl";
import liquidMetalFrag from "@/shaders/liquid-metal.frag.glsl";
import flowingRibbonsFrag from "@/shaders/flowing-ribbons.frag.glsl";
import stripeRibbonsFrag from "@/shaders/stripe-ribbons.frag.glsl";
import neonWaveLinesFrag from "@/shaders/neon-wave-lines.frag.glsl";
import glassPanelsFrag from "@/shaders/glass-panels.frag.glsl";

export const PRESET_SHADERS: ShaderData[] = [
  {
    id: "preset-fbm-noise",
    name: "FBM Noise Flow",
    description: "Animated fractal Brownian motion noise with mouse-reactive hotspots",
    mode: "2d",
    fragmentShader: default2dFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uSpeed", label: "Speed", type: "float", min: 0, max: 2, step: 0.01, default: 0.3 },
      { name: "uScale", label: "Scale", type: "float", min: 0.5, max: 10, step: 0.1, default: 3.0 },
      { name: "uMouseRadius", label: "Mouse Radius", type: "float", min: 0, max: 1, step: 0.01, default: 0.5 },
    ],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isPreset: true,
  },
  {
    id: "preset-3d-fresnel",
    name: "Fresnel Glow",
    description: "3D object with dual-light setup, specular highlights and fresnel rim glow",
    mode: "3d",
    geometry: "sphere",
    fragmentShader: default3dFrag,
    vertexShader: default3dVert,
    controls: [
      { name: "uFresnelPower", label: "Fresnel Power", type: "float", min: 0.5, max: 8, step: 0.1, default: 3.0 },
      { name: "uSpecPower", label: "Specular Power", type: "float", min: 4, max: 128, step: 1, default: 64 },
    ],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
    isPreset: true,
  },
  {
    id: "preset-blue-glitch",
    name: "Blue Glitch",
    description: "Blocky glitch pixels over white, blue palette, denser in the middle, slow flicker",
    mode: "2d",
    fragmentShader: blueGlitchFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uPixelCount", label: "Pixel Count", type: "float", min: 20, max: 200, step: 1, default: 80 },
      { name: "uDensity", label: "Density", type: "float", min: 0.1, max: 1.0, step: 0.01, default: 0.7 },
      { name: "uSpeed", label: "Speed", type: "float", min: 0.1, max: 3.0, step: 0.05, default: 0.5 },
      { name: "uFalloff", label: "Edge Falloff", type: "float", min: 0.3, max: 5.0, step: 0.1, default: 1.2 },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-liquid-metal",
    name: "Liquid Metal",
    description: "Flowing liquid metallic waves with specular highlights and fresnel reflections",
    mode: "2d",
    fragmentShader: liquidMetalFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uWaveScale", label: "Wave Scale", type: "float", min: 0.5, max: 5.0, step: 0.1, default: 1.8 },
      { name: "uSpeed", label: "Speed", type: "float", min: 0.05, max: 1.5, step: 0.05, default: 0.35 },
      { name: "uDistortion", label: "Distortion", type: "float", min: 0, max: 3.0, step: 0.05, default: 1.2 },
      { name: "uReflection", label: "Reflection", type: "float", min: 0, max: 2.0, step: 0.05, default: 1.0 },
      { name: "uMetalColor", label: "Color 1", type: "color", default: [0.75, 0.78, 0.85] },
      { name: "uMetalColor2", label: "Color 2", type: "color", default: [0.85, 0.65, 0.4] },
      { name: "uGradientMix", label: "Gradient Mix", type: "float", min: 0, max: 1, step: 0.01, default: 0.0 },
      { name: "uGradientAngle", label: "Gradient Angle", type: "float", min: 0, max: 1, step: 0.01, default: 0.25 },
      { name: "uRainbow", label: "Rainbow Iridescence", type: "bool", default: 0 },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-flowing-ribbons",
    name: "Flowing Ribbons",
    description: "Smooth colorful ribbons flowing over a white background — orange, pink, lavender",
    mode: "2d",
    fragmentShader: flowingRibbonsFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uRibbonCount", label: "Ribbon Count", type: "float", min: 1, max: 16, step: 1, default: 5 },
      { name: "uSpeed", label: "Speed", type: "float", min: 0.05, max: 1.5, step: 0.05, default: 0.4 },
      { name: "uRibbonWidth", label: "Ribbon Width", type: "float", min: 0.02, max: 0.3, step: 0.005, default: 0.12 },
      { name: "uCurvature", label: "Curvature", type: "float", min: 0.05, max: 0.6, step: 0.01, default: 0.25 },
      { name: "uSoftness", label: "Edge Softness", type: "float", min: 0.01, max: 0.5, step: 0.01, default: 0.02 },
      { name: "uIntensity", label: "Intensity", type: "float", min: 0.3, max: 1.0, step: 0.01, default: 0.9 },
      { name: "uDirection", label: "Direction", type: "float", min: 0, max: 1, step: 0.01, default: 0.92 },
      { name: "uRandomWidth", label: "Random Width", type: "bool", default: 1 },
      { name: "uRandomCurve", label: "Random Curvature", type: "bool", default: 1 },
      { name: "uRandomSpeed", label: "Random Speed", type: "bool", default: 1 },
      { name: "uRandomDir", label: "Random Direction", type: "bool", default: 0 },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-stripe-ribbons-webgl",
    name: "Stripe Ribbons (WebGL)",
    description: "Option A — 7 layered ribbons with noise, HSL gradients, glow bloom, and mouse influence",
    mode: "2d",
    fragmentShader: stripeRibbonsFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uSpeed", label: "Speed", type: "float", min: 0.05, max: 0.8, step: 0.05, default: 0.2 },
      { name: "uRibbonWidth", label: "Ribbon Width", type: "float", min: 0.01, max: 0.15, step: 0.005, default: 0.035 },
      { name: "uGlow", label: "Glow", type: "float", min: 0, max: 2.0, step: 0.1, default: 0.6 },
      { name: "uMouseInfluence", label: "Mouse Influence", type: "float", min: 0, max: 2.0, step: 0.05, default: 1.0 },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-stripe-ribbons-canvas",
    name: "Stripe Ribbons (Canvas 2D)",
    description: "Option B — Bezier curve ribbons with screen blending, gradients, and mouse drift",
    mode: "canvas2d",
    fragmentShader: "",
    vertexShader: "",
    controls: [],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-stripe-gradient",
    name: "Stripe Gradient (Original)",
    description: "Option C — Reverse-engineered Stripe.com animated wave gradient with WebGL2",
    mode: "stripeGradient",
    fragmentShader: "",
    vertexShader: "",
    controls: [
      { name: "uColorCount", label: "Color Count", type: "float", min: 2, max: 6, step: 1, default: 4 },
      { name: "uColor1", label: "Color 1", type: "color", default: [0.94, 0.0, 0.56] },
      { name: "uColor2", label: "Color 2", type: "color", default: [0.43, 0.76, 0.96] },
      { name: "uColor3", label: "Color 3", type: "color", default: [0.44, 0.22, 1.0] },
      { name: "uColor4", label: "Color 4", type: "color", default: [1.0, 0.73, 0.15] },
      { name: "uColor5", label: "Color 5", type: "color", default: [0.0, 0.77, 1.0] },
      { name: "uColor6", label: "Color 6", type: "color", default: [1.0, 0.42, 0.42] },
      { name: "uAmplitude", label: "Amplitude", type: "float", min: 0, max: 1000, step: 10, default: 320 },
      { name: "uSpeed", label: "Speed", type: "float", min: 0, max: 5, step: 0.05, default: 1.25 },
      { name: "uSeed", label: "Seed", type: "float", min: 0, max: 100, step: 1, default: 0 },
      { name: "uFps", label: "FPS", type: "float", min: 10, max: 60, step: 1, default: 24 },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-neon-wave-lines",
    name: "Neon Wave Lines",
    description: "Bundle of flowing parallel neon lines sweeping in an S-curve — amber to magenta to purple",
    mode: "2d",
    fragmentShader: neonWaveLinesFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uLineCount", label: "Line Count", type: "float", min: 5, max: 60, step: 1, default: 35 },
      { name: "uSpeed", label: "Speed", type: "float", min: 0, max: 2, step: 0.01, default: 0.5 },
      { name: "uTwist", label: "Twist", type: "float", min: 0, max: 4, step: 0.05, default: 1.0 },
      { name: "uAmplitude", label: "Wave Amplitude", type: "float", min: 0, max: 0.15, step: 0.005, default: 0.02 },
      { name: "uSpread", label: "Line Spread", type: "float", min: 0.01, max: 0.6, step: 0.005, default: 0.18 },
      { name: "uLineWidth", label: "Line Width", type: "float", min: 0.5, max: 5, step: 0.1, default: 1.5 },
      { name: "uGlowIntensity", label: "Glow Intensity", type: "float", min: 0, max: 3, step: 0.05, default: 1.0 },
      { name: "uCurvature", label: "Curvature", type: "float", min: 0, max: 2, step: 0.05, default: 1.0 },
      { name: "uColor1", label: "Color 1 (Start)", type: "color", default: [1.0, 0.75, 0.3] },
      { name: "uColor2", label: "Color 2", type: "color", default: [0.92, 0.2, 0.65] },
      { name: "uColor3", label: "Color 3", type: "color", default: [0.6, 0.15, 0.88] },
      { name: "uColor4", label: "Color 4 (End)", type: "color", default: [0.35, 0.1, 0.55] },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
  {
    id: "preset-glass-panels",
    name: "Glass Panels",
    description: "Frosted glass panes with refraction and blur over a cursor-following sphere",
    mode: "2d",
    fragmentShader: glassPanelsFrag,
    vertexShader: fullscreenVert,
    controls: [
      { name: "uPaneCount", label: "Pane Count", type: "float", min: 2, max: 20, step: 1, default: 8 },
      { name: "uPaneAngle", label: "Pane Angle", type: "float", min: -90, max: 90, step: 1, default: -38 },
      { name: "uPaneWidth", label: "Pane Width", type: "float", min: 0.02, max: 0.4, step: 0.005, default: 0.17 },
      { name: "uGapWidth", label: "Gap Width", type: "float", min: 0.0, max: 0.1, step: 0.002, default: 0.0 },
      { name: "uRefraction", label: "Refraction", type: "float", min: 0, max: 5, step: 0.05, default: 3.0 },
      { name: "uWarp", label: "Warp Intensity", type: "float", min: 0, max: 3, step: 0.05, default: 1.0 },
      { name: "uBlurStrength", label: "Glass Blur", type: "float", min: 0, max: 5, step: 0.1, default: 5.0 },
      { name: "uPaneEdge", label: "Edge Sharpness", type: "float", min: 0.1, max: 5, step: 0.1, default: 2.1 },
      { name: "uSphereRadius", label: "Sphere Size", type: "float", min: 0.5, max: 8, step: 0.1, default: 4.7 },
      { name: "uSphereBlur", label: "Sphere Softness", type: "float", min: 0.1, max: 5, step: 0.1, default: 5.0 },
      { name: "uSphereLayerBlur", label: "Sphere Layer Blur", type: "float", min: 0, max: 5, step: 0.1, default: 1.0 },
      { name: "uRainbow", label: "Rainbow Tint", type: "float", min: 0, max: 3, step: 0.05, default: 0.0 },
      { name: "uBgColor", label: "Background", type: "color", default: [0.12, 0.12, 0.12] },
      { name: "uSphereColor", label: "Sphere Color", type: "color", default: [0.9, 0.25, 0.15] },
    ],
    createdAt: Date.now(),
    updatedAt: Date.now(),
    isPreset: true,
  },
];
